// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * susfs_kpm - KernelPatch Module reimplementation of susfs4ksu for APatch
 *
 * Target: android15-6.6 GKI kernel.
 *
 * User-space protocol (via sc_kpm_control, ctl_args is a NUL-terminated string):
 *   "<CMD_HEX_UPPER>|<arg1>|<arg2>|..."
 * Example:
 *   "55550|/data/adb/ksu"                       -> add_sus_path
 *   "55590|4.14.310|#1 SMP PREEMPT ..."         -> set_uname
 *   "555A0|1"                                   -> enable_log
 *   "555E1|"                                    -> show version (writes to out_msg)
 *
 * The KPM was generated by forking sidex15/susfs4ksu-module and re-targeting
 * it at APatch/KernelPatch instead of KernelSU.  Hook implementation follows
 * the same approach as upstream susfs (path_openat / show_mountinfo / etc.)
 * but uses KernelPatch's inline-hook + kallsyms_lookup_name APIs so that no
 * kernel source patch is required.
 */
#include <compiler.h>
#include <kpmodule.h>
#include <hook.h>
#include <kallsyms.h>
#include <linux/printk.h>
#include <linux/string.h>
#include <linux/stddef.h>
#include <uapi/asm-generic/errno.h>
#include <kputils.h>
#include <log.h>

#include "include/susfs_kpm.h"

KPM_NAME(SUSFS_KPM_NAME);
KPM_VERSION(SUSFS_KPM_VERSION);
KPM_LICENSE("GPL v2");
KPM_AUTHOR("susfs4ap");
KPM_DESCRIPTION("susfs reimplementation for APatch via KPM (android15-6.6)");

/* Prevent GCC from collapsing indirect BLR into direct BL — KPM is ~47GB
 * away from KP's .text, exceeding BL's ±128MB range. */
#define HIDE_PTR(ptr) __asm__("" : "=r"(ptr) : "0"(ptr))

/* ===== text-protocol helpers ===== */

static int hex_to_uint(const char *s, unsigned int *out) {
    unsigned int v = 0;
    if (!s || !*s) return -1;
    while (*s) {
        char c = *s;
        unsigned int d;
        if (c >= '0' && c <= '9') d = c - '0';
        else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
        else return -1;
        v = (v << 4) | d;
        s++;
    }
    *out = v;
    return 0;
}

/* Split ctl_args on '|' into argv-like array (in place). Returns argc. */
static int split_fields(char *buf, char **fields, int max_fields) {
    int n = 0;
    char *p = buf;
    if (n < max_fields) fields[n++] = p;
    while (*p) {
        if (*p == '|') {
            *p = '\0';
            if (n < max_fields) {
                fields[n++] = p + 1;
            } else {
                return -1;
            }
        }
        p++;
    }
    return n;
}

static long parse_long(const char *s, long def) {
    if (!s || !*s) return def;
    char *end = 0;
    long v = 0;
    /* strtoul/strtol not exported — do it by hand */
    int neg = 0;
    if (*s == '-') { neg = 1; s++; }
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return neg ? -v : v;
}

static unsigned long parse_ulong(const char *s, unsigned long def) {
    if (!s || !*s) return def;
    unsigned long v = 0;
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return v;
}

/* ===== init / exit ===== */

static long susfs_init(const char *args, const char *event, void *reserved)
{
    logki("susfs_kpm: init, event=%s args=%s\n", event ? event : "(null)",
          args ? args : "(null)");

    int rc = 0;
    rc |= susfs_sus_path_init_hooks();
    rc |= susfs_open_redirect_init_hooks();
    rc |= susfs_sus_mount_init_hooks();
    rc |= susfs_sus_kstat_init_hooks();
    rc |= susfs_sus_map_init_hooks();
    rc |= susfs_set_uname_init_hooks();
    rc |= susfs_set_cmdline_init_hooks();

    if (rc) {
        logke("susfs_kpm: one or more hook installations failed (rc=%d), "
              "feature will be degraded\n", rc);
    }
    logki("susfs_kpm: init complete\n");
    return 0;
}

static long susfs_exit(void *reserved)
{
    logki("susfs_kpm: exit, unhooking everything\n");
    susfs_sus_path_cleanup();
    susfs_open_redirect_cleanup();
    susfs_sus_mount_cleanup();
    susfs_sus_kstat_cleanup();
    susfs_sus_map_cleanup();
    susfs_set_uname_cleanup();
    susfs_set_cmdline_cleanup();
    return 0;
}

/* ===== ctl0: dispatch text-protocol commands from userspace ===== */

/* field accessor — no nested functions in kernel mode */
#define ARG(i) ((i) < argc ? fields[(i)] : "")

static long susfs_ctl0(const char *ctl_args, char *__user out_msg, int outlen)
{
    if (!ctl_args || !*ctl_args) return -EINVAL;

    /* ctl_args is read-only — copy to a local mutable buffer.  2048 matches
     * the userspace kpm_send() buffer so messages are never truncated. */
    static char buf[2048];
    int n = 0;
    while (ctl_args[n] && n < (int)sizeof(buf) - 1) {
        buf[n] = ctl_args[n];
        n++;
    }
    buf[n] = '\0';

    char *fields[16];
    int argc = split_fields(buf, fields, 16);
    if (argc < 1) return -EINVAL;

    unsigned int cmd;
    if (hex_to_uint(fields[0], &cmd) != 0) {
        return -EINVAL;
    }

    switch (cmd) {
    case CMD_SUSFS_ADD_SUS_PATH:
        return susfs_add_sus_path(ARG(1), 0);
    case CMD_SUSFS_ADD_SUS_PATH_LOOP:
        return susfs_add_sus_path(ARG(1), 1);
    case CMD_SUSFS_ADD_OPEN_REDIRECT:
        if (argc < 4) return -EINVAL;
        return susfs_add_open_redirect(ARG(1), ARG(2),
                                       (int)parse_long(ARG(3), 0));
    case CMD_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU:
        return susfs_set_hide_sus_mnts((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY:
    case CMD_SUSFS_ADD_SUS_KSTAT:
    case CMD_SUSFS_UPDATE_SUS_KSTAT: {
        /* Unified protocol for all sus_kstat commands:
         *   cmd|path|target_ino|spoofed_ino|spoofed_dev|spoofed_nlink|
         *   spoofed_size|spoofed_atime_sec|spoofed_atime_nsec|
         *   spoofed_mtime_sec|spoofed_mtime_nsec|spoofed_ctime_sec|
         *   spoofed_ctime_nsec|spoofed_blocks|spoofed_blksize[|flags]
         * 14 fields after cmd => argc must be >= 15.  An optional 15th
         * field carries the spoof flags (defaults to 0).  Userspace
         * resolves "default" sentinels / current stat values before
         * sending, so the KPM just stores them as-is.  is_static is set
         * only for the _statically variant. */
        if (argc < 15) return -EINVAL;
        int is_static = (cmd == CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY) ? 1 : 0;
        int kflags = (argc >= 16) ? (int)parse_long(ARG(15), 0) : 0;
        return susfs_add_sus_kstat(
            ARG(1),                              /* path */
            parse_ulong(ARG(2), 0),              /* target_ino */
            parse_ulong(ARG(3), 0),              /* spoofed_ino */
            parse_ulong(ARG(4), 0),              /* spoofed_dev */
            (unsigned int)parse_ulong(ARG(5), 0),/* spoofed_nlink */
            (long long)parse_long(ARG(6), 0),    /* spoofed_size */
            parse_long(ARG(7), 0),               /* spoofed_atime_sec */
            parse_ulong(ARG(8), 0),              /* spoofed_atime_nsec */
            parse_long(ARG(9), 0),               /* spoofed_mtime_sec */
            parse_ulong(ARG(10), 0),             /* spoofed_mtime_nsec */
            parse_long(ARG(11), 0),              /* spoofed_ctime_sec */
            parse_ulong(ARG(12), 0),             /* spoofed_ctime_nsec */
            (long long)parse_long(ARG(13), 0),   /* spoofed_blocks */
            parse_long(ARG(14), 0),              /* spoofed_blksize */
            kflags,
            is_static);
    }
    case CMD_SUSFS_ADD_SUS_MAP:
        if (argc < 2) return -EINVAL;
        return susfs_add_sus_map(ARG(1));
    case CMD_SUSFS_SET_UNAME:
        if (argc < 3) return -EINVAL;
        return susfs_set_uname(ARG(1), ARG(2));
    case CMD_SUSFS_SET_CMDLINE_OR_BOOTCONFIG:
        if (argc < 2) return -EINVAL;
        return susfs_set_cmdline_or_bootconfig(ARG(1));
    case CMD_SUSFS_ENABLE_LOG:
        return susfs_set_log_enabled((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_ENABLE_AVC_LOG_SPOOFING:
        return susfs_set_avc_log_spoofing((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_SHOW_VERSION: {
        char tmp[SUSFS_MAX_VERSION_BUFSIZE];
        int rc2 = susfs_show_version(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_ENABLED_FEATURES: {
        char tmp[SUSFS_ENABLED_FEATURES_SIZE];
        int rc2 = susfs_show_enabled_features(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_VARIANT: {
        char tmp[SUSFS_MAX_VARIANT_BUFSIZE];
        int rc2 = susfs_show_variant(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    default:
        logke("susfs_kpm: unknown cmd 0x%x\n", cmd);
        return -ENOSYS;
    }
}

KPM_INIT(susfs_init);
KPM_CTL0(susfs_ctl0);
KPM_EXIT(susfs_exit);
