// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * susfs_kpm - KernelPatch Module reimplementation of susfs4ksu for APatch
 *
 * Target: android15-6.6 GKI kernel.
 *
 * User-space protocol (via sc_kpm_control, ctl_args is a NUL-terminated string):
 *   "<CMD_HEX_UPPER>|<arg1>|<arg2>|..."
 * Example:
 *   "55550|/data/adb/ksu"                       -> add_sus_path
 *   "55590|4.14.310|#1 SMP PREEMPT ..."         -> set_uname
 *   "555A0|1"                                   -> enable_log
 *   "555E1|"                                    -> show version (writes to out_msg)
 *
 * The KPM was generated by forking sidex15/susfs4ksu-module and re-targeting
 * it at APatch/KernelPatch instead of KernelSU.  Hook implementation follows
 * the same approach as upstream susfs (path_openat / show_mountinfo / etc.)
 * but uses KernelPatch's inline-hook + kallsyms_lookup_name APIs so that no
 * kernel source patch is required.
 */
#include <compiler.h>
#include <kpmodule.h>
#include <hook.h>
#include <kallsyms.h>
#include <linux/printk.h>
#include <linux/string.h>
#include <linux/stddef.h>
/* <linux/spinlock.h> for DEFINE_SPINLOCK; the feature sources under
 * features/ each include their own copy, and this keeps spinlock_t /
 * raw-spinlock types visible in this translation unit as well. */
#include <linux/spinlock.h>
#include <uapi/asm-generic/errno.h>
#include <kputils.h>
#include <log.h>
#include <syscall.h>
#include <linux/uaccess.h>

#include "include/susfs_kpm.h"

KPM_NAME(SUSFS_KPM_NAME);
KPM_VERSION(SUSFS_KPM_VERSION);
KPM_LICENSE("GPL v2");
KPM_AUTHOR("susfs4ap");
KPM_DESCRIPTION("susfs reimplementation for APatch via KPM (android15-6.6)");

/* Prevent GCC from collapsing indirect BLR into direct BL — KPM is ~47GB
 * away from KP's .text, exceeding BL's ±128MB range. */
#define HIDE_PTR(ptr) __asm__("" : "=r"(ptr) : "0"(ptr))

/* ===== kfunc resolvers — definitions =====
 *
 * These are the actual storage for the externs declared in susfs_kpm.h.
 * They are resolved via kallsyms_lookup_name() in susfs_init() before any
 * feature hook is installed, so every feature file can rely on them being
 * non-NULL once init returns.  See the big comment in susfs_kpm.h for why
 * the kf_* pointers from KernelPatch's headers cannot be used directly.
 */
void *(*susfs_memcpy)(void *, const void *, __kernel_size_t);
void *(*susfs_memset)(void *, int, __kernel_size_t);
int   (*susfs_strcmp)(const char *, const char *);
int   (*susfs_memcmp)(const void *, const void *, __kernel_size_t);
void *(*susfs_kzalloc_real)(size_t, gfp_t);
int   susfs_kzalloc_fallback = 0;
void  (*susfs_kfree)(const void *);
void *(*susfs_vmalloc)(unsigned long);
void  (*susfs_vfree)(const void *);
void  (*susfs__raw_spin_lock)(void *);
void  (*susfs__raw_spin_unlock)(void *);
int (*susfs_printk)(const char *fmt, ...);

/* kzalloc wrapper — uses kzalloc/kzalloc.cfi_jt/__kzalloc if available,
 * otherwise falls back to __kmalloc + memset.  This is needed because on
 * many GKI kernels "kzalloc" is not in kallsyms (inlined or renamed). */
void *susfs_kzalloc(size_t size, gfp_t flags)
{
    if (susfs_kzalloc_real) {
        if (susfs_kzalloc_fallback && susfs_memset) {
            void *p = susfs_kzalloc_real(size, flags);
            if (p) susfs_memset(p, 0, size);
            return p;
        }
        return susfs_kzalloc_real(size, flags);
    }
    return NULL;
}

/* ===== version-tolerant symbol resolution — see susfs_kpm.h ===== */

/* KernelPatch's export-table query (kernel/base/symbol.c; KP_EXPORT_SYMBOL'd
 * and advertised in KP_FEATURES as "symbol_lookup_name").  Declared here rather
 * than by including KernelPatch's private <symbol.h>.  Exported since
 * KernelPatch 0.13.3, i.e. below the 0.13.9 floor this module already has
 * because of hook_syscalln_override, so importing it costs no compatibility. */
extern unsigned long symbol_lookup_name(const char *name);

/* KernelPatch's own version, packed as (major << 16) | (minor << 8) | patch
 * (kernel/include/common.h:VERSION).  Exported since 0.4.0 — diagnostics only. */
extern uint32_t kpver;

susfs_klns_t susfs_kallsyms_by_suffix;

/* Toolchain suffixes we try ourselves, after the exact lookup and
 * KernelPatch's scan both missed.  Deliberately narrow:
 *
 *   .cfi_jt      CFI jump-table stub — same ABI, and the entry point that is
 *                actually callable on a CFI kernel.  KernelPatch's own scan
 *                skips these on purpose (symbol_has_compiler_suffix() rejects
 *                any name containing a "cfi" component), so this is the one
 *                case its scan cannot cover and we must.
 *   .cold        cold-section clone — same ABI.
 *   .constprop.0, .isra.0
 *                first-generation clones.  These normally keep the signature,
 *                but a constprop clone can drop an argument that was constant
 *                at every call site, so they are accepted only as a last
 *                resort and only at init time.
 *   .part.N      NOT tried: a ".part" symbol is a fragment of a function, not
 *                a callable whole, so it cannot stand in for its base name.
 *   .llvm.<n>    NOT tried: the hash is not predictable — that case is exactly
 *                what KernelPatch's scan (step 2) exists for.
 *
 * Every candidate is only reached after an exact-match miss, so kernels whose
 * symbols are unrenamed pay nothing for this list. */
static const char *const susfs_ksym_suffixes[] = {
    ".cfi_jt", ".cold", ".constprop.0", ".isra.0",
};
#define SUSFS_KSYM_SUFFIX_COUNT \
    (sizeof(susfs_ksym_suffixes) / sizeof(susfs_ksym_suffixes[0]))
#define SUSFS_KSYM_BUF 96

static unsigned long susfs_ksym_try_suffixes(const char *name)
{
    char buf[SUSFS_KSYM_BUF];
    unsigned int i, j;
    size_t n = 0;

    /* No strcpy/strlen/strcat here: KernelPatch's <linux/string.h> wrappers
     * call the unresolvable kf_* pointers (see susfs_kpm.h), and this also runs
     * before susfs_strcmp/susfs_memcpy are resolved.  Plain byte loops are safe
     * because the Makefile builds with -fno-builtin, so clang never rewrites
     * them into memcpy() calls. */
    while (name[n]) {
        if (n + 1 >= SUSFS_KSYM_BUF) return 0; /* too long to extend */
        buf[n] = name[n];
        n++;
    }

    for (i = 0; i < SUSFS_KSYM_SUFFIX_COUNT; i++) {
        const char *sfx = susfs_ksym_suffixes[i];
        size_t k = n;

        for (j = 0; sfx[j]; j++) {
            if (k + 1 >= SUSFS_KSYM_BUF) break;
            buf[k++] = sfx[j];
        }
        if (sfx[j]) continue; /* candidate did not fit — skip it */
        buf[k] = '\0';
        if (kallsyms_lookup_name) {
            unsigned long addr = kallsyms_lookup_name(buf);
            if (addr) return addr;
        }
    }
    return 0;
}

unsigned long susfs_ksym(const char *name)
{
    unsigned long addr;

    if (!name || !*name) return 0;

    if (kallsyms_lookup_name) {
        addr = kallsyms_lookup_name(name);
        if (addr) return addr;
    }
    if (susfs_kallsyms_by_suffix) {
        addr = susfs_kallsyms_by_suffix(name);
        if (addr) return addr;
    }
    return susfs_ksym_try_suffixes(name);
}

/* Bind KernelPatch's suffix scan when the running KernelPatch has it.  Called
 * at the very top of susfs_init(), before anything is resolved, so every
 * lookup below already benefits from it.  On older KernelPatch this is a no-op
 * and susfs_ksym() degrades to the exact lookup plus the suffix list above. */
void susfs_ksym_init(void)
{
    /* symbol_lookup_name() is imported, not probed: the KPM loader resolves it
     * at load time or the whole load fails, so testing it for NULL would just
     * be an always-true comparison.  It is the *result* that can be NULL, when
     * the running KernelPatch predates kallsyms_lookup_name_by_suffix. */
    unsigned long p = symbol_lookup_name("kallsyms_lookup_name_by_suffix");
    if (p) susfs_kallsyms_by_suffix = (susfs_klns_t)p;
}

/* ===== text-protocol helpers ===== */

static int hex_to_uint(const char *s, unsigned int *out) {
    unsigned int v = 0;
    if (!s || !*s) return -1;
    while (*s) {
        char c = *s;
        unsigned int d;
        if (c >= '0' && c <= '9') d = c - '0';
        else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
        else return -1;
        v = (v << 4) | d;
        s++;
    }
    *out = v;
    return 0;
}

/* Split ctl_args on '|' into argv-like array (in place). Returns argc. */
static int split_fields(char *buf, char **fields, int max_fields) {
    int n = 0;
    char *p = buf;
    if (n < max_fields) fields[n++] = p;
    while (*p) {
        if (*p == '|') {
            *p = '\0';
            if (n < max_fields) {
                fields[n++] = p + 1;
            } else {
                return -1;
            }
        }
        p++;
    }
    return n;
}

static long parse_long(const char *s, long def) {
    if (!s || !*s) return def;
    char *end = 0;
    long v = 0;
    /* strtoul/strtol not exported — do it by hand */
    int neg = 0;
    if (*s == '-') { neg = 1; s++; }
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return neg ? -v : v;
}

static unsigned long parse_ulong(const char *s, unsigned long def) {
    if (!s || !*s) return def;
    unsigned long v = 0;
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return v;
}

/* ===== init / exit ===== */

/* No-op stand-ins for _raw_spin_lock / _raw_spin_unlock when the kernel
 * doesn't export them (some PREEMPT configs inline these away).  The hooks
 * still function — the spinlock just becomes a NOP, which is acceptable
 * because hook paths are short and races are extremely unlikely on a
 * non-preempt GKI kernel. */
static void susfs_nop_spin_lock(void *lock) { (void)lock; }
static void susfs_nop_spin_unlock(void *lock) { (void)lock; }

/* Tracks whether the mandatory core symbols were resolved.  If not, ctl0
 * commands return -ENOSYS so userspace sees a clean error instead of a
 * NULL-deref panic. */
static int susfs_core_symbols_ok = 0;

/* Forward declaration — before_cmd_channel is defined after susfs_init
 * but referenced by it (for hook_syscalln). */
static void before_cmd_channel(hook_fargs5_t *args, void *udata);

static long susfs_init(const char *args, const char *event, void *reserved)
{
    logki("susfs_kpm: init, event=%s args=%s\n", event ? event : "(null)",
          args ? args : "(null)");

    /* Bind KernelPatch's kallsyms_lookup_name_by_suffix() (when this
     * KernelPatch has it) before anything below is resolved, so every lookup
     * in this function already goes through susfs_ksym() with the suffix scan
     * available.  See the version-tolerant resolution block above. */
    susfs_ksym_init();

    /* Resolve the kernel functions we need through kallsyms_lookup_name
     * (which IS exported by KernelPatch) instead of the unresolvable kf_*
     * pointers that KernelPatch's <linux/string.h> / <linux/spinlock.h>
     * inline wrappers reference.  Feature files call these susfs_* globals
     * for every memcpy/memset/strcmp/memcmp/kzalloc/kfree/spin_lock op.
     *
     * On Android 15+ GKI kernels with CFI enabled, many function symbols
     * are emitted as "<name>.cfi_jt" (jump table) rather than "<name>".
     * KernelPatch's own kfunc_match_cfi() macro handles this by trying the
     * ".cfi_jt" suffix first, then falling back to the bare name.  We
     * replicate that logic here with the resolve_cfi() helper. */
    susfs_memcpy = (typeof(susfs_memcpy))susfs_ksym("memcpy");
    susfs_memset = (typeof(susfs_memset))susfs_ksym("memset");
    susfs_strcmp = (typeof(susfs_strcmp))susfs_ksym("strcmp");
    susfs_memcmp = (typeof(susfs_memcmp))susfs_ksym("memcmp");
    susfs_kzalloc_real = (typeof(susfs_kzalloc_real))susfs_ksym("kzalloc");
    susfs_kfree = (typeof(susfs_kfree))susfs_ksym("kfree");
    susfs_vmalloc = (typeof(susfs_vmalloc))susfs_ksym("vmalloc");
    susfs_vfree = (typeof(susfs_vfree))susfs_ksym("vfree");
    susfs__raw_spin_lock =
        (typeof(susfs__raw_spin_lock))susfs_ksym("_raw_spin_lock");
    susfs__raw_spin_unlock =
        (typeof(susfs__raw_spin_unlock))susfs_ksym("_raw_spin_unlock");

    /* CFI fallback: try "<sym>.cfi_jt" for symbols that resolved to NULL.
     * On CFI-enabled GKI kernels, many functions (memcpy, memset, etc.)
     * are only exported with the .cfi_jt suffix. */
    if (!susfs_memcpy)
        susfs_memcpy = (typeof(susfs_memcpy))susfs_ksym("memcpy.cfi_jt");
    if (!susfs_memset)
        susfs_memset = (typeof(susfs_memset))susfs_ksym("memset.cfi_jt");
    if (!susfs_strcmp)
        susfs_strcmp = (typeof(susfs_strcmp))susfs_ksym("strcmp.cfi_jt");
    if (!susfs_memcmp)
        susfs_memcmp = (typeof(susfs_memcmp))susfs_ksym("memcmp.cfi_jt");
    if (!susfs_kfree)
        susfs_kfree = (typeof(susfs_kfree))susfs_ksym("kfree.cfi_jt");
    if (!susfs_vmalloc)
        susfs_vmalloc = (typeof(susfs_vmalloc))susfs_ksym("vmalloc.cfi_jt");
    if (!susfs_vfree)
        susfs_vfree = (typeof(susfs_vfree))susfs_ksym("vfree.cfi_jt");
    if (!susfs__raw_spin_lock)
        susfs__raw_spin_lock =
            (typeof(susfs__raw_spin_lock))susfs_ksym("_raw_spin_lock.cfi_jt");
    if (!susfs__raw_spin_unlock)
        susfs__raw_spin_unlock =
            (typeof(susfs__raw_spin_unlock))susfs_ksym("_raw_spin_unlock.cfi_jt");

    /* kzalloc is often inlined or renamed on GKI kernels.  Try multiple
     * fallbacks in order of preference:
     *   1. "kzalloc.cfi_jt"  — CFI jump table variant
     *   2. "__kzalloc"       — some kernels export this instead
     *   3. "__kmalloc" + memset — last resort: allocate then zero-fill
     * We store a flag so susfs_kzalloc() wrapper can fall back to
     * __kmalloc+memset at call time if needed. */
    if (!susfs_kzalloc_real) {
        susfs_kzalloc_real = (typeof(susfs_kzalloc_real))susfs_ksym("kzalloc.cfi_jt");
    }
    if (!susfs_kzalloc_real) {
        susfs_kzalloc_real = (typeof(susfs_kzalloc_real))susfs_ksym("__kzalloc");
    }
    /* If still not found, use __kmalloc + memset as a last resort. */
    if (!susfs_kzalloc_real) {
        void *(*kmalloc_fn)(size_t, gfp_t) =
            (typeof(kmalloc_fn))susfs_ksym("__kmalloc");
        if (!kmalloc_fn)
            kmalloc_fn = (typeof(kmalloc_fn))susfs_ksym("__kmalloc.cfi_jt");
        if (kmalloc_fn && susfs_memset) {
            susfs_kzalloc_real = kmalloc_fn;
            susfs_kzalloc_fallback = 1;
            logkw("susfs_kpm: kzalloc not found, using __kmalloc+memset fallback\n");
        }
    }
    /* kfree fallback: if "kfree" not found, try "__kfree" — though kfree
     * is usually present. */
    if (!susfs_kfree) {
        susfs_kfree = (typeof(susfs_kfree))susfs_ksym("__kfree");
    }

    /* Fall back to no-op spinlocks if the real ones aren't found. */
    if (!susfs__raw_spin_lock) {
        logkw("susfs_kpm: _raw_spin_lock not found, using no-op\n");
        susfs__raw_spin_lock = susfs_nop_spin_lock;
    }
    if (!susfs__raw_spin_unlock) {
        logkw("susfs_kpm: _raw_spin_unlock not found, using no-op\n");
        susfs__raw_spin_unlock = susfs_nop_spin_unlock;
    }

    /* Resolve printk so we can write to the regular kernel log buffer
     * (dmesg).  logki/log_boot only reach KernelPatch's internal boot log,
     * which userspace cannot read without an authed SUPERCALL_BOOTLOG.
     *
     * The ksu_susfs CLI also cannot reach SUPERCALL_KPM_CONTROL: in KP's
     * supercall dispatch (kernel/patch/common/supercall.c) KPM_CONTROL sits
     * behind `if (!is_authed) return -EPERM;`.  is_authed is granted only
     * by (a) a correct superkey via auth_superkey(), or (b) being the
     * trusted manager UID (APK signature SHA256 match in userd.c).  ksu_susfs
     * is neither — it's a third-party binary (no APK signature match) and
     * passes "su" as the key, which has no special meaning in this dispatch
     * path (the "su" string is only special-cased in handle_supercmd() for
     * the /system/bin/kp su-shell route).  SU-allowed UIDs only get
     * is_trusted_caller=1, not is_authed, so they pass SUPERCALL_SU but are
     * blocked at the KPM_CONTROL gate.  Hence dmesg is the only reliable
     * userspace channel.
     *
     * By printk-ing "susfs_kpm: loaded ..." at init, post-fs-data.sh /
     * boot-completed.sh detect the KPM via `dmesg | grep susfs_kpm` without
     * any supercall.  Try the bare name, the .cfi_jt CFI jump-table variant,
     * and the _printk rename used on kernels that reworked the printk export. */
    susfs_printk = (typeof(susfs_printk))susfs_ksym("printk");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))susfs_ksym("printk.cfi_jt");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))susfs_ksym("_printk");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))susfs_ksym("_printk.cfi_jt");

    /* The string/mem and allocation symbols are mandatory — without them
     * the feature files cannot function.  But we MUST NOT fail the load
     * (returning non-zero causes the KP loader to reject the KPM).  Instead
     * we record the failure and let ctl0 return -ENOSYS per command.
     *
     * For kzalloc we accept either a real kzalloc or the __kmalloc+memset
     * fallback (susfs_kzalloc_real non-NULL means the wrapper works). */
    if (!susfs_memcpy || !susfs_memset || !susfs_strcmp || !susfs_memcmp ||
        !susfs_kzalloc_real || !susfs_kfree) {
        logke("susfs_kpm: failed to resolve core kernel symbols "
              "(memcpy=%px memset=%px strcmp=%px memcmp=%px "
              "kzalloc_real=%px kfree=%px)\n",
              susfs_memcpy, susfs_memset, susfs_strcmp, susfs_memcmp,
              susfs_kzalloc_real, susfs_kfree);
        susfs_core_symbols_ok = 0;
    } else {
        susfs_core_symbols_ok = 1;
    }

    /* Always attempt hook installation — individual features log their own
     * errors and degrade gracefully.  Never return non-zero: the KP loader
     * treats init() failure as a fatal "KPM load failed". */
    int rc = 0;
    rc |= susfs_sus_path_init_hooks();
    rc |= susfs_open_redirect_init_hooks();
    rc |= susfs_sus_mount_init_hooks();
    rc |= susfs_sus_kstat_init_hooks();
    rc |= susfs_sus_map_init_hooks();
    rc |= susfs_set_uname_init_hooks();
    rc |= susfs_set_cmdline_init_hooks();
    rc |= susfs_avc_log_spoofing_init_hooks();

    if (rc) {
        logke("susfs_kpm: one or more hook installations failed (rc=%d), "
              "feature will be degraded\n", rc);
    }
    logki("susfs_kpm: init complete (core_symbols=%d)\n", susfs_core_symbols_ok);

    /* Emit status to the regular kernel log (dmesg) so userspace can
     * detect the KPM without an authed SUPERCALL_KPM_CONTROL.  The module
     * scripts grep for "susfs_kpm" in dmesg to set the susfs_active flag,
     * and ksu_susfs show version/features/variant parse these lines.
     * logki above only reaches KP's internal boot log, not dmesg.
     *
     * We emit four machine-parseable lines:
     *   susfs_kpm: version=<v> variant=<v> core_symbols=<0|1>
     *   susfs_kpm: features=<comma-separated CONFIG_KSU_SUSFS_* list>
     *   susfs_kpm: ksym by_suffix=<0|1> kpver=<x.y.z>
     *   susfs_kpm: loaded
     * Userspace greps "susfs_kpm:" and parses key=value pairs. */
    if (susfs_printk) {
        susfs_printk("susfs_kpm: version=%s variant=%s core_symbols=%d\n",
                     SUSFS_KPM_VERSION, SUSFS_KPM_VARIANT, susfs_core_symbols_ok);
        susfs_printk("susfs_kpm: features=%s\n",
                     "CONFIG_KSU_SUSFS_SUS_PATH,"
                     "CONFIG_KSU_SUSFS_SUS_MOUNT,"
                     "CONFIG_KSU_SUSFS_SUS_KSTAT,"
                     "CONFIG_KSU_SUSFS_OPEN_REDIRECT,"
                     "CONFIG_KSU_SUSFS_SUS_MAP,"
                     "CONFIG_KSU_SUSFS_SPOOF_UNAME,"
                     "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG,"
                     "CONFIG_KSU_SUSFS_ENABLE_LOG,"
                     "CONFIG_KSU_SUSFS_ENABLE_AVC_LOG_SPOOFING,"
                     "CONFIG_KSU_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU_PROCS,"
                     "CONFIG_KSU_SUSFS_TRY_UMOUNT,"
                     "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT,"
                     "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT,"
                     "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT");
        /* Resolution diagnostics: which suffix-tolerant path is live, and the
         * KernelPatch version behind it.  Machine-parseable so a report from a
         * different kernel/APatch combination answers "why did symbol X not
         * resolve" without a rebuild.  kpver is (major<<16)|(minor<<8)|patch. */
        susfs_printk("susfs_kpm: ksym by_suffix=%d kpver=%u.%u.%u\n",
                     susfs_kallsyms_by_suffix ? 1 : 0,
                     (kpver >> 16) & 0xff, (kpver >> 8) & 0xff, kpver & 0xff);
        susfs_printk("susfs_kpm: loaded\n");
    }

    /* Install the syscall command channel (hook __NR_kcmp).
     * This lets ksu_susfs control the KPM without supercall/is_authed —
     * critical for WebUI functionality on APatch without a preset superkey.
     * See before_cmd_channel() below for details.
     *
     * MUST use hook_syscalln_override(), NOT hook_syscalln():
     * a callback may only suppress the real syscall (args->skip_origin=1,
     * args->ret=<result>) when the slot was registered with allow_skip=1.
     * hook_syscalln() registers with allow_skip=0, so KernelPatch refuses the
     * skip and the real kcmp(pid1=<magic>,...) still executes — returning
     * -ESRCH to userspace and making EVERY command look like a failure
     * (this was the "susfs module not running" bug: reads worked because the
     * reply buffer was still written, but userspace discarded it and fell
     * back to dmesg/diag parsing, so the WebUI saw 1 of 14 features).
     * hook_syscalln_override() sets allow_skip=1 + bypass_gate=1 and, when
     * the global dispatcher is hooked at el0_svc_common (handler granularity
     * unavailable), transparently falls back to the per-syscall mechanism,
     * which implements skip_origin at handler granularity. */
    hook_err_t hook_rc = hook_syscalln_override(__NR_kcmp, 5, before_cmd_channel, 0, 0);
    if (hook_rc != HOOK_NO_ERR) {
        logke("susfs_kpm: failed to hook __NR_kcmp for cmd channel (rc=%d)\n",
              hook_rc);
        if (susfs_printk) {
            susfs_printk("susfs_kpm: WARNING: cmd channel hook failed, "
                         "WebUI features will not work (rc=%d)\n", hook_rc);
        }
    } else {
        logki("susfs_kpm: cmd channel hooked on __NR_kcmp (override mode)\n");
        if (susfs_printk) {
            susfs_printk("susfs_kpm: cmd_channel=enabled\n");
            /* Machine-readable marker so scripts/userspace can tell an
             * override-mode KPM (returns the real rc via skip_origin and via
             * the optional 5th-arg result pointer) from an old one that
             * leaked -ESRCH. */
            susfs_printk("susfs_kpm: cmd_channel_mode=override\n");
        }
    }

    return 0;
}

static long susfs_exit(void *reserved)
{
    logki("susfs_kpm: exit, unhooking everything\n");
    unhook_syscalln(__NR_kcmp, before_cmd_channel, 0);
    susfs_sus_path_cleanup();
    susfs_open_redirect_cleanup();
    susfs_sus_mount_cleanup();
    susfs_sus_kstat_cleanup();
    susfs_sus_map_cleanup();
    susfs_set_uname_cleanup();
    susfs_set_cmdline_cleanup();
    susfs_avc_log_spoofing_cleanup();
    return 0;
}

/* ===== ctl0: dispatch text-protocol commands from userspace ===== */

/* field accessor — no nested functions in kernel mode */
#define ARG(i) ((i) < argc ? fields[(i)] : "")

static long susfs_ctl0(const char *ctl_args, char *__user out_msg, int outlen)
{
    if (!ctl_args || !*ctl_args) return -EINVAL;

    /* ctl_args is read-only — copy to a local mutable buffer.  2048 matches
     * the userspace kpm_send() buffer so messages are never truncated. */
    static char buf[2048];
    int n = 0;
    while (ctl_args[n] && n < (int)sizeof(buf) - 1) {
        buf[n] = ctl_args[n];
        n++;
    }
    buf[n] = '\0';

    char *fields[16];
    int argc = split_fields(buf, fields, 16);
    if (argc < 1) return -EINVAL;

    unsigned int cmd;
    if (hex_to_uint(fields[0], &cmd) != 0) {
        return -EINVAL;
    }

    /* show_* commands are pure state and don't touch kernel memory/strings,
     * so they work even if core symbols weren't resolved.  All other
     * commands need memcpy/memset/strcmp/kzalloc/kfree. */
    if (!susfs_core_symbols_ok &&
        cmd != CMD_SUSFS_SHOW_VERSION &&
        cmd != CMD_SUSFS_SHOW_ENABLED_FEATURES &&
        cmd != CMD_SUSFS_SHOW_VARIANT) {
        return -ENOSYS;
    }

    switch (cmd) {
    case CMD_SUSFS_ADD_SUS_PATH:
        return susfs_add_sus_path(ARG(1), 0);
    case CMD_SUSFS_ADD_SUS_PATH_LOOP:
        return susfs_add_sus_path(ARG(1), 1);
    case CMD_SUSFS_ADD_OPEN_REDIRECT:
        if (argc < 4) return -EINVAL;
        return susfs_add_open_redirect(ARG(1), ARG(2),
                                       (int)parse_long(ARG(3), 0));
    case CMD_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU:
        return susfs_set_hide_sus_mnts((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_UMOUNT_FOR_ZYGOTE_ISO_SERVICE:
        /* [deprecated] upstream dropped the zygote-isolation umount when it
         * reworked try_umount.  Kept as an advisory no-op so scripts that
         * still poke it succeed instead of aborting. */
        return 0;
    case CMD_SUSFS_SET_ANDROID_DATA_ROOT_PATH:
    case CMD_SUSFS_SET_SDCARD_ROOT_PATH:
        /* [deprecated] upstream removed the root-path configuration knobs.
         * This KPM hooks path_openat directly and never needed them. */
        return 0;
    case CMD_SUSFS_SUS_SU:
    case CMD_SUSFS_SHOW_SUS_SU_WORKING_MODE:
    case CMD_SUSFS_IS_SUS_SU_READY:
        /* [deprecated] sus_su was removed in susfs v2.0; there is no
         * kernel-side sus_su to report on.  Report "not supported" (rather
         * than -ENOSYS, which userspace reads as "KPM not loaded") so
         * callers fall back to their own sus_su handling. */
        return -EOPNOTSUPP;
    case CMD_SUSFS_ADD_TRY_UMOUNT:
        if (argc < 2) return -EINVAL;
        return susfs_add_try_umount(ARG(1), (int)parse_long(ARG(2), 0));
    case CMD_SUSFS_ADD_SUS_MOUNT:
        /* add_sus_mount: record path for /proc/mounts hiding (mode=0,
         * no umount).  Uses the same try_umount list as add_try_umount
         * but with mode=0 so the path is only hidden, not detached. */
        if (argc < 2) return -EINVAL;
        return susfs_add_try_umount(ARG(1), 0);
    case CMD_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT:
        return susfs_auto_add_try_umount_for_bind_mount();
    case CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY:
    case CMD_SUSFS_ADD_SUS_KSTAT:
    case CMD_SUSFS_UPDATE_SUS_KSTAT: {
        /* Unified protocol for all sus_kstat commands:
         *   cmd|path|target_ino|spoofed_ino|spoofed_dev|spoofed_nlink|
         *   spoofed_size|spoofed_atime_sec|spoofed_atime_nsec|
         *   spoofed_mtime_sec|spoofed_mtime_nsec|spoofed_ctime_sec|
         *   spoofed_ctime_nsec|spoofed_blocks|spoofed_blksize[|flags]
         * 14 fields after cmd => argc must be >= 15.  An optional 15th
         * field carries the spoof flags (defaults to 0).  Userspace
         * resolves "default" sentinels / current stat values before
         * sending, so the KPM just stores them as-is.  is_static is set
         * only for the _statically variant.
         *
         * UPDATE is a different operation (upstream
         * susfs_update_sus_kstat): the path was bind-mounted/overlaid since
         * add_sus_kstat, so its inode changed — the stored spoof values are
         * kept and only target_ino/target_dev are swapped.  It fails with
         * -ENOENT if the path was never added. */
        if (argc < 15) return -EINVAL;
        int is_static = (cmd == CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY) ? 1 : 0;
        int kflags = (argc >= 16) ? (int)parse_long(ARG(15), 0) : 0;
        if (cmd == CMD_SUSFS_UPDATE_SUS_KSTAT) {
            return susfs_update_sus_kstat(
                ARG(1), parse_ulong(ARG(2), 0), parse_ulong(ARG(3), 0),
                parse_ulong(ARG(4), 0), (unsigned int)parse_ulong(ARG(5), 0),
                (long long)parse_long(ARG(6), 0), parse_long(ARG(7), 0),
                parse_ulong(ARG(8), 0), parse_long(ARG(9), 0),
                parse_ulong(ARG(10), 0), parse_long(ARG(11), 0),
                parse_ulong(ARG(12), 0), (long long)parse_long(ARG(13), 0),
                parse_long(ARG(14), 0), kflags);
        }
        return susfs_add_sus_kstat(
            ARG(1),                              /* path */
            parse_ulong(ARG(2), 0),              /* target_ino */
            parse_ulong(ARG(3), 0),              /* spoofed_ino */
            parse_ulong(ARG(4), 0),              /* spoofed_dev */
            (unsigned int)parse_ulong(ARG(5), 0),/* spoofed_nlink */
            (long long)parse_long(ARG(6), 0),    /* spoofed_size */
            parse_long(ARG(7), 0),               /* spoofed_atime_sec */
            parse_ulong(ARG(8), 0),              /* spoofed_atime_nsec */
            parse_long(ARG(9), 0),               /* spoofed_mtime_sec */
            parse_ulong(ARG(10), 0),             /* spoofed_mtime_nsec */
            parse_long(ARG(11), 0),              /* spoofed_ctime_sec */
            parse_ulong(ARG(12), 0),             /* spoofed_ctime_nsec */
            (long long)parse_long(ARG(13), 0),   /* spoofed_blocks */
            parse_long(ARG(14), 0),              /* spoofed_blksize */
            kflags,
            is_static);
    }
    case CMD_SUSFS_ADD_SUS_MAP:
        if (argc < 2) return -EINVAL;
        return susfs_add_sus_map(ARG(1));
    case CMD_SUSFS_SET_UNAME:
        if (argc < 3) return -EINVAL;
        return susfs_set_uname(ARG(1), ARG(2));
    case CMD_SUSFS_SET_CMDLINE_OR_BOOTCONFIG:
        if (argc < 2) return -EINVAL;
        return susfs_set_cmdline_or_bootconfig(ARG(1));
    case CMD_SUSFS_ENABLE_LOG:
        return susfs_set_log_enabled((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_ENABLE_AVC_LOG_SPOOFING:
        return susfs_set_avc_log_spoofing((int)parse_long(ARG(1), 0));
    /* The E7 dcache engine's commands (0x55565-0x5556a) are NOT served here any
     * more: they belong to the separate mount_kpm package (mountkpm/), which
     * owns its own command channel magic.  A dcache command that somehow lands
     * on this engine's channel falls through to the default case and answers
     * -ENOSYS, which is exactly how userspace tells the two engines apart. */
    case CMD_SUSFS_SHOW_VERSION: {
        char tmp[SUSFS_MAX_VERSION_BUFSIZE];
        int rc2 = susfs_show_version(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_ENABLED_FEATURES: {
        char tmp[SUSFS_ENABLED_FEATURES_SIZE];
        int rc2 = susfs_show_enabled_features(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_VARIANT: {
        char tmp[SUSFS_MAX_VARIANT_BUFSIZE];
        int rc2 = susfs_show_variant(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    default:
        logke("susfs_kpm: unknown cmd 0x%x\n", cmd);
        return -ENOSYS;
    }
}

KPM_INIT(susfs_init);
KPM_CTL0(susfs_ctl0);
KPM_EXIT(susfs_exit);

/* ===== syscall command channel (bypasses supercall is_authed gate) =====
 *
 * SUPERCALL_KPM_CONTROL requires is_authed, which is only granted to the
 * APatch trusted-manager UID or a correct superkey.  ksu_susfs runs in a
 * root shell (uid 0) — neither — so supercall always returns -EPERM.
 *
 * To let ksu_susfs (and thus the WebUI) actually control the KPM, we hook
 * __NR_kcmp (syscall 272) — a rarely-used syscall (compares two processes'
 * resources) — and use it as a command channel.  When userspace calls:
 *
 *   syscall(272, SUSFS_CMD_MAGIC, cmd_buf_ptr, out_buf_ptr, out_buf_len,
 *           rc_out_ptr)
 *
 * the before callback checks the magic; if it matches, it reads cmd_buf
 * from userspace, dispatches via susfs_ctl0(), writes the result to
 * out_buf, publishes the real return value through rc_out_ptr (optional:
 * it must be NULL or point to an int pre-set to SUSFS_RC_SENTINEL — see
 * rc_out_is_armed()), and short-circuits the original kcmp syscall.
 * Non-magic calls pass through to the real kcmp unchanged.
 *
 * IMPORTANT — hook_syscalln_override() is mandatory here.  KernelPatch only
 * honours skip_origin for slots registered with allow_skip=1; plain
 * hook_syscalln() sets allow_skip=0, so the kernel keeps the real
 * kcmp(pid1=<magic>, pid2=<cmd_ptr>, ...) call, which returns -ESRCH
 * ("No such process") to userspace and made every command look failed.
 * Between that and the before-hook the reply buffer IS written, so reads
 * still returned data — which is exactly why the failure was silent: the
 * CLI saw rc=-1, discarded the buffer, and fell back to parsing dmesg (which
 * had already rotated) and then the diag file (which only stored the first
 * feature on its "features:" line).  Result: the WebUI reported 1 of 14
 * features and the module looked dead while the KPM was actually loaded.
 *
 * rc_out_ptr makes the protocol independent of skip support: even if a
 * future kernel refuses skip_origin again, userspace still learns the real
 * rc, and the stray kcmp call is harmless (it only looks up pids).
 *
 * __NR_kcmp is chosen because:
 *   - It exists on all Android 4.x+ kernels (arm64).
 *   - Normal apps never call it (it's for debug/analysis tools like perf).
 *   - It takes 5 args (pid1, pid2, type, idx1, idx2) so we have room for
 *     magic + cmd_buf + out_buf + out_len + rc_out.
 */

#define __NR_kcmp 272
#define SUSFS_CMD_MAGIC 0x5355534653595343ULL /* "SUSFSYSC" */

/* Largest plausible user-space address (arm64 48-bit VA).  Used to reject
 * garbage in the optional rc-out pointer before handing it to
 * compat_copy_to_user(). */
#define SUSFS_USER_ADDR_MAX (1UL << 48)

/* The rc-out pointer is opt-in and *armed* by userspace: the int it points to
 * must pre-store this sentinel.  The handshake matters because old userspace
 * passes only four arguments, so x4 holds whatever the caller left there (a
 * length, a stale register, ...).  Writing the result unconditionally would
 * poke 4 bytes into a random address of the calling process; with the check an
 * unarmed pointer is only ever *read*, once, by a bounded copy. */
#define SUSFS_RC_SENTINEL 0x7fffffff

/* 1 only when *p holds SUSFS_RC_SENTINEL, i.e. the caller opted in. */
static int rc_out_is_armed(int __user *p)
{
    int probe;
    long n;

    if (!p) return 0;
    if ((unsigned long)p >= SUSFS_USER_ADDR_MAX) return 0;
    if (((unsigned long)p & (sizeof(int) - 1)) != 0) return 0;
    /* compat_strncpy_from_user stops at NUL.  The sentinel contains no NUL
     * byte, so only a full 4-byte read means the value really is the sentinel
     * (a garbage pointer either faults — negative return — or reads something
     * else). */
    n = compat_strncpy_from_user((char *)&probe, (const char __user *)p,
                                 sizeof(probe));
    if (n != (long)sizeof(probe)) return 0;
    return probe == SUSFS_RC_SENTINEL;
}

static void before_cmd_channel(hook_fargs5_t *args, void *udata)
{
    /* On arm64 GKI, has_syscall_wrapper=1 so arg0 is pt_regs*.  Use
     * syscall_argn() to get the real arguments. */
    uint64_t magic = syscall_argn(args, 0);
    if (magic != SUSFS_CMD_MAGIC) return; /* not ours — pass through */

    const char __user *cmd_buf = (const char __user *)syscall_argn(args, 1);
    char __user *out_buf = (char __user *)syscall_argn(args, 2);
    int out_len = (int)syscall_argn(args, 3);
    /* Optional 5th argument: int* receiving the real return value.  Only
     * written when userspace armed it with SUSFS_RC_SENTINEL. */
    int __user *rc_out = (int __user *)syscall_argn(args, 4);
    int rc_out_ok = rc_out_is_armed(rc_out);

    /* Read command string from userspace */
    char cmd[2048];
    int n = compat_strncpy_from_user(cmd, cmd_buf, sizeof(cmd) - 1);
    if (n <= 0) {
        if (rc_out_ok) {
            int e = -EINVAL;
            compat_copy_to_user(rc_out, &e, sizeof(e));
        }
        args->skip_origin = 1;
        args->ret = (uint64_t)(long)-EINVAL;
        return;
    }
    cmd[n] = '\0';

    /* Dispatch via the same ctl0 handler used by supercall */
    long rc = susfs_ctl0(cmd, out_buf, out_len);

    /* Publish the real rc where skip_origin cannot be relied upon. */
    if (rc_out_ok) {
        int rv = (int)rc;
        compat_copy_to_user(rc_out, &rv, sizeof(rv));
    }

    /* Short-circuit the original kcmp syscall; return rc as the result.
     * Honoured thanks to hook_syscalln_override() (allow_skip=1). */
    args->skip_origin = 1;
    args->ret = (uint64_t)(long)rc;
}
