// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * susfs_kpm - KernelPatch Module reimplementation of susfs4ksu for APatch
 *
 * Target: android15-6.6 GKI kernel.
 *
 * User-space protocol (via sc_kpm_control, ctl_args is a NUL-terminated string):
 *   "<CMD_HEX_UPPER>|<arg1>|<arg2>|..."
 * Example:
 *   "55550|/data/adb/ksu"                       -> add_sus_path
 *   "55590|4.14.310|#1 SMP PREEMPT ..."         -> set_uname
 *   "555A0|1"                                   -> enable_log
 *   "555E1|"                                    -> show version (writes to out_msg)
 *
 * The KPM was generated by forking sidex15/susfs4ksu-module and re-targeting
 * it at APatch/KernelPatch instead of KernelSU.  Hook implementation follows
 * the same approach as upstream susfs (path_openat / show_mountinfo / etc.)
 * but uses KernelPatch's inline-hook + kallsyms_lookup_name APIs so that no
 * kernel source patch is required.
 */
#include <compiler.h>
#include <kpmodule.h>
#include <hook.h>
#include <kallsyms.h>
#include <linux/printk.h>
#include <linux/string.h>
#include <linux/stddef.h>
#include <uapi/asm-generic/errno.h>
#include <kputils.h>
#include <log.h>
#include <syscall.h>
#include <linux/uaccess.h>

#include "include/susfs_kpm.h"

KPM_NAME(SUSFS_KPM_NAME);
KPM_VERSION(SUSFS_KPM_VERSION);
KPM_LICENSE("GPL v2");
KPM_AUTHOR("susfs4ap");
KPM_DESCRIPTION("susfs reimplementation for APatch via KPM (android15-6.6)");

/* Prevent GCC from collapsing indirect BLR into direct BL — KPM is ~47GB
 * away from KP's .text, exceeding BL's ±128MB range. */
#define HIDE_PTR(ptr) __asm__("" : "=r"(ptr) : "0"(ptr))

/* ===== kfunc resolvers — definitions =====
 *
 * These are the actual storage for the externs declared in susfs_kpm.h.
 * They are resolved via kallsyms_lookup_name() in susfs_init() before any
 * feature hook is installed, so every feature file can rely on them being
 * non-NULL once init returns.  See the big comment in susfs_kpm.h for why
 * the kf_* pointers from KernelPatch's headers cannot be used directly.
 */
void *(*susfs_memcpy)(void *, const void *, __kernel_size_t);
void *(*susfs_memset)(void *, int, __kernel_size_t);
int   (*susfs_strcmp)(const char *, const char *);
int   (*susfs_memcmp)(const void *, const void *, __kernel_size_t);
void *(*susfs_kzalloc_real)(size_t, gfp_t);
int   susfs_kzalloc_fallback = 0;
void  (*susfs_kfree)(const void *);
void *(*susfs_vmalloc)(unsigned long);
void  (*susfs_vfree)(const void *);
void  (*susfs__raw_spin_lock)(void *);
void  (*susfs__raw_spin_unlock)(void *);
int (*susfs_printk)(const char *fmt, ...);

/* kzalloc wrapper — uses kzalloc/kzalloc.cfi_jt/__kzalloc if available,
 * otherwise falls back to __kmalloc + memset.  This is needed because on
 * many GKI kernels "kzalloc" is not in kallsyms (inlined or renamed). */
void *susfs_kzalloc(size_t size, gfp_t flags)
{
    if (susfs_kzalloc_real) {
        if (susfs_kzalloc_fallback && susfs_memset) {
            void *p = susfs_kzalloc_real(size, flags);
            if (p) susfs_memset(p, 0, size);
            return p;
        }
        return susfs_kzalloc_real(size, flags);
    }
    return NULL;
}

/* ===== text-protocol helpers ===== */

static int hex_to_uint(const char *s, unsigned int *out) {
    unsigned int v = 0;
    if (!s || !*s) return -1;
    while (*s) {
        char c = *s;
        unsigned int d;
        if (c >= '0' && c <= '9') d = c - '0';
        else if (c >= 'a' && c <= 'f') d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F') d = c - 'A' + 10;
        else return -1;
        v = (v << 4) | d;
        s++;
    }
    *out = v;
    return 0;
}

/* Split ctl_args on '|' into argv-like array (in place). Returns argc. */
static int split_fields(char *buf, char **fields, int max_fields) {
    int n = 0;
    char *p = buf;
    if (n < max_fields) fields[n++] = p;
    while (*p) {
        if (*p == '|') {
            *p = '\0';
            if (n < max_fields) {
                fields[n++] = p + 1;
            } else {
                return -1;
            }
        }
        p++;
    }
    return n;
}

static long parse_long(const char *s, long def) {
    if (!s || !*s) return def;
    char *end = 0;
    long v = 0;
    /* strtoul/strtol not exported — do it by hand */
    int neg = 0;
    if (*s == '-') { neg = 1; s++; }
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return neg ? -v : v;
}

static unsigned long parse_ulong(const char *s, unsigned long def) {
    if (!s || !*s) return def;
    unsigned long v = 0;
    while (*s >= '0' && *s <= '9') {
        v = v * 10 + (*s - '0');
        s++;
    }
    if (*s != '\0') return def;
    return v;
}

/* ===== init / exit ===== */

/* No-op stand-ins for _raw_spin_lock / _raw_spin_unlock when the kernel
 * doesn't export them (some PREEMPT configs inline these away).  The hooks
 * still function — the spinlock just becomes a NOP, which is acceptable
 * because hook paths are short and races are extremely unlikely on a
 * non-preempt GKI kernel. */
static void susfs_nop_spin_lock(void *lock) { (void)lock; }
static void susfs_nop_spin_unlock(void *lock) { (void)lock; }

/* Tracks whether the mandatory core symbols were resolved.  If not, ctl0
 * commands return -ENOSYS so userspace sees a clean error instead of a
 * NULL-deref panic. */
static int susfs_core_symbols_ok = 0;

/* Forward declaration — before_cmd_channel is defined after susfs_init
 * but referenced by it (for hook_syscalln). */
static void before_cmd_channel(hook_fargs5_t *args, void *udata);

static long susfs_init(const char *args, const char *event, void *reserved)
{
    logki("susfs_kpm: init, event=%s args=%s\n", event ? event : "(null)",
          args ? args : "(null)");

    /* Resolve the kernel functions we need through kallsyms_lookup_name
     * (which IS exported by KernelPatch) instead of the unresolvable kf_*
     * pointers that KernelPatch's <linux/string.h> / <linux/spinlock.h>
     * inline wrappers reference.  Feature files call these susfs_* globals
     * for every memcpy/memset/strcmp/memcmp/kzalloc/kfree/spin_lock op.
     *
     * On Android 15+ GKI kernels with CFI enabled, many function symbols
     * are emitted as "<name>.cfi_jt" (jump table) rather than "<name>".
     * KernelPatch's own kfunc_match_cfi() macro handles this by trying the
     * ".cfi_jt" suffix first, then falling back to the bare name.  We
     * replicate that logic here with the resolve_cfi() helper. */
    susfs_memcpy = (typeof(susfs_memcpy))kallsyms_lookup_name("memcpy");
    susfs_memset = (typeof(susfs_memset))kallsyms_lookup_name("memset");
    susfs_strcmp = (typeof(susfs_strcmp))kallsyms_lookup_name("strcmp");
    susfs_memcmp = (typeof(susfs_memcmp))kallsyms_lookup_name("memcmp");
    susfs_kzalloc_real = (typeof(susfs_kzalloc_real))kallsyms_lookup_name("kzalloc");
    susfs_kfree = (typeof(susfs_kfree))kallsyms_lookup_name("kfree");
    susfs_vmalloc = (typeof(susfs_vmalloc))kallsyms_lookup_name("vmalloc");
    susfs_vfree = (typeof(susfs_vfree))kallsyms_lookup_name("vfree");
    susfs__raw_spin_lock =
        (typeof(susfs__raw_spin_lock))kallsyms_lookup_name("_raw_spin_lock");
    susfs__raw_spin_unlock =
        (typeof(susfs__raw_spin_unlock))kallsyms_lookup_name("_raw_spin_unlock");

    /* CFI fallback: try "<sym>.cfi_jt" for symbols that resolved to NULL.
     * On CFI-enabled GKI kernels, many functions (memcpy, memset, etc.)
     * are only exported with the .cfi_jt suffix. */
    if (!susfs_memcpy)
        susfs_memcpy = (typeof(susfs_memcpy))kallsyms_lookup_name("memcpy.cfi_jt");
    if (!susfs_memset)
        susfs_memset = (typeof(susfs_memset))kallsyms_lookup_name("memset.cfi_jt");
    if (!susfs_strcmp)
        susfs_strcmp = (typeof(susfs_strcmp))kallsyms_lookup_name("strcmp.cfi_jt");
    if (!susfs_memcmp)
        susfs_memcmp = (typeof(susfs_memcmp))kallsyms_lookup_name("memcmp.cfi_jt");
    if (!susfs_kfree)
        susfs_kfree = (typeof(susfs_kfree))kallsyms_lookup_name("kfree.cfi_jt");
    if (!susfs_vmalloc)
        susfs_vmalloc = (typeof(susfs_vmalloc))kallsyms_lookup_name("vmalloc.cfi_jt");
    if (!susfs_vfree)
        susfs_vfree = (typeof(susfs_vfree))kallsyms_lookup_name("vfree.cfi_jt");
    if (!susfs__raw_spin_lock)
        susfs__raw_spin_lock =
            (typeof(susfs__raw_spin_lock))kallsyms_lookup_name("_raw_spin_lock.cfi_jt");
    if (!susfs__raw_spin_unlock)
        susfs__raw_spin_unlock =
            (typeof(susfs__raw_spin_unlock))kallsyms_lookup_name("_raw_spin_unlock.cfi_jt");

    /* kzalloc is often inlined or renamed on GKI kernels.  Try multiple
     * fallbacks in order of preference:
     *   1. "kzalloc.cfi_jt"  — CFI jump table variant
     *   2. "__kzalloc"       — some kernels export this instead
     *   3. "__kmalloc" + memset — last resort: allocate then zero-fill
     * We store a flag so susfs_kzalloc() wrapper can fall back to
     * __kmalloc+memset at call time if needed. */
    if (!susfs_kzalloc_real) {
        susfs_kzalloc_real = (typeof(susfs_kzalloc_real))kallsyms_lookup_name("kzalloc.cfi_jt");
    }
    if (!susfs_kzalloc_real) {
        susfs_kzalloc_real = (typeof(susfs_kzalloc_real))kallsyms_lookup_name("__kzalloc");
    }
    /* If still not found, use __kmalloc + memset as a last resort. */
    if (!susfs_kzalloc_real) {
        void *(*kmalloc_fn)(size_t, gfp_t) =
            (typeof(kmalloc_fn))kallsyms_lookup_name("__kmalloc");
        if (!kmalloc_fn)
            kmalloc_fn = (typeof(kmalloc_fn))kallsyms_lookup_name("__kmalloc.cfi_jt");
        if (kmalloc_fn && susfs_memset) {
            susfs_kzalloc_real = kmalloc_fn;
            susfs_kzalloc_fallback = 1;
            logkw("susfs_kpm: kzalloc not found, using __kmalloc+memset fallback\n");
        }
    }
    /* kfree fallback: if "kfree" not found, try "__kfree" — though kfree
     * is usually present. */
    if (!susfs_kfree) {
        susfs_kfree = (typeof(susfs_kfree))kallsyms_lookup_name("__kfree");
    }

    /* Fall back to no-op spinlocks if the real ones aren't found. */
    if (!susfs__raw_spin_lock) {
        logkw("susfs_kpm: _raw_spin_lock not found, using no-op\n");
        susfs__raw_spin_lock = susfs_nop_spin_lock;
    }
    if (!susfs__raw_spin_unlock) {
        logkw("susfs_kpm: _raw_spin_unlock not found, using no-op\n");
        susfs__raw_spin_unlock = susfs_nop_spin_unlock;
    }

    /* Resolve printk so we can write to the regular kernel log buffer
     * (dmesg).  logki/log_boot only reach KernelPatch's internal boot log,
     * which userspace cannot read without an authed SUPERCALL_BOOTLOG.
     *
     * The ksu_susfs CLI also cannot reach SUPERCALL_KPM_CONTROL: in KP's
     * supercall dispatch (kernel/patch/common/supercall.c) KPM_CONTROL sits
     * behind `if (!is_authed) return -EPERM;`.  is_authed is granted only
     * by (a) a correct superkey via auth_superkey(), or (b) being the
     * trusted manager UID (APK signature SHA256 match in userd.c).  ksu_susfs
     * is neither — it's a third-party binary (no APK signature match) and
     * passes "su" as the key, which has no special meaning in this dispatch
     * path (the "su" string is only special-cased in handle_supercmd() for
     * the /system/bin/kp su-shell route).  SU-allowed UIDs only get
     * is_trusted_caller=1, not is_authed, so they pass SUPERCALL_SU but are
     * blocked at the KPM_CONTROL gate.  Hence dmesg is the only reliable
     * userspace channel.
     *
     * By printk-ing "susfs_kpm: loaded ..." at init, post-fs-data.sh /
     * boot-completed.sh detect the KPM via `dmesg | grep susfs_kpm` without
     * any supercall.  Try the bare name, the .cfi_jt CFI jump-table variant,
     * and the _printk rename used on kernels that reworked the printk export. */
    susfs_printk = (typeof(susfs_printk))kallsyms_lookup_name("printk");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))kallsyms_lookup_name("printk.cfi_jt");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))kallsyms_lookup_name("_printk");
    if (!susfs_printk)
        susfs_printk = (typeof(susfs_printk))kallsyms_lookup_name("_printk.cfi_jt");

    /* The string/mem and allocation symbols are mandatory — without them
     * the feature files cannot function.  But we MUST NOT fail the load
     * (returning non-zero causes the KP loader to reject the KPM).  Instead
     * we record the failure and let ctl0 return -ENOSYS per command.
     *
     * For kzalloc we accept either a real kzalloc or the __kmalloc+memset
     * fallback (susfs_kzalloc_real non-NULL means the wrapper works). */
    if (!susfs_memcpy || !susfs_memset || !susfs_strcmp || !susfs_memcmp ||
        !susfs_kzalloc_real || !susfs_kfree) {
        logke("susfs_kpm: failed to resolve core kernel symbols "
              "(memcpy=%px memset=%px strcmp=%px memcmp=%px "
              "kzalloc_real=%px kfree=%px)\n",
              susfs_memcpy, susfs_memset, susfs_strcmp, susfs_memcmp,
              susfs_kzalloc_real, susfs_kfree);
        susfs_core_symbols_ok = 0;
    } else {
        susfs_core_symbols_ok = 1;
    }

    /* Always attempt hook installation — individual features log their own
     * errors and degrade gracefully.  Never return non-zero: the KP loader
     * treats init() failure as a fatal "KPM load failed". */
    int rc = 0;
    rc |= susfs_sus_path_init_hooks();
    rc |= susfs_open_redirect_init_hooks();
    rc |= susfs_sus_mount_init_hooks();
    rc |= susfs_sus_kstat_init_hooks();
    rc |= susfs_sus_map_init_hooks();
    rc |= susfs_set_uname_init_hooks();
    rc |= susfs_set_cmdline_init_hooks();

    if (rc) {
        logke("susfs_kpm: one or more hook installations failed (rc=%d), "
              "feature will be degraded\n", rc);
    }
    logki("susfs_kpm: init complete (core_symbols=%d)\n", susfs_core_symbols_ok);

    /* Emit status to the regular kernel log (dmesg) so userspace can
     * detect the KPM without an authed SUPERCALL_KPM_CONTROL.  The module
     * scripts grep for "susfs_kpm" in dmesg to set the susfs_active flag,
     * and ksu_susfs show version/features/variant parse these lines.
     * logki above only reaches KP's internal boot log, not dmesg.
     *
     * We emit three machine-parseable lines:
     *   susfs_kpm: version=<v> variant=<v> core_symbols=<0|1>
     *   susfs_kpm: features=<comma-separated CONFIG_KSU_SUSFS_* list>
     *   susfs_kpm: loaded
     * Userspace greps "susfs_kpm:" and parses key=value pairs. */
    if (susfs_printk) {
        susfs_printk("susfs_kpm: version=%s variant=%s core_symbols=%d\n",
                     SUSFS_KPM_VERSION, SUSFS_KPM_VARIANT, susfs_core_symbols_ok);
        susfs_printk("susfs_kpm: features=%s\n",
                     "CONFIG_KSU_SUSFS_SUS_PATH,"
                     "CONFIG_KSU_SUSFS_SUS_MOUNT,"
                     "CONFIG_KSU_SUSFS_SUS_KSTAT,"
                     "CONFIG_KSU_SUSFS_OPEN_REDIRECT,"
                     "CONFIG_KSU_SUSFS_SUS_MAP,"
                     "CONFIG_KSU_SUSFS_SET_UNAME,"
                     "CONFIG_KSU_SUSFS_SPOOF_CMDLINE,"
                     "CONFIG_KSU_SUSFS_ENABLE_LOG,"
                     "CONFIG_KSU_SUSFS_ENABLE_AVC_LOG_SPOOFING,"
                     "CONFIG_KSU_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU_PROCS");
        susfs_printk("susfs_kpm: loaded\n");
    }

    /* Install the syscall command channel (hook __NR_kcmp).
     * This lets ksu_susfs control the KPM without supercall/is_authed —
     * critical for WebUI functionality on APatch without a preset superkey.
     * See before_cmd_channel() below for details. */
    hook_err_t hook_rc = hook_syscalln(__NR_kcmp, 5, before_cmd_channel, 0, 0);
    if (hook_rc != HOOK_NO_ERR) {
        logke("susfs_kpm: failed to hook __NR_kcmp for cmd channel (rc=%d)\n",
              hook_rc);
        if (susfs_printk) {
            susfs_printk("susfs_kpm: WARNING: cmd channel hook failed, "
                         "WebUI features will not work (rc=%d)\n", hook_rc);
        }
    } else {
        logki("susfs_kpm: cmd channel hooked on __NR_kcmp\n");
        if (susfs_printk) {
            susfs_printk("susfs_kpm: cmd_channel=enabled\n");
        }
    }

    return 0;
}

static long susfs_exit(void *reserved)
{
    logki("susfs_kpm: exit, unhooking everything\n");
    unhook_syscalln(__NR_kcmp, before_cmd_channel, 0);
    susfs_sus_path_cleanup();
    susfs_open_redirect_cleanup();
    susfs_sus_mount_cleanup();
    susfs_sus_kstat_cleanup();
    susfs_sus_map_cleanup();
    susfs_set_uname_cleanup();
    susfs_set_cmdline_cleanup();
    return 0;
}

/* ===== ctl0: dispatch text-protocol commands from userspace ===== */

/* field accessor — no nested functions in kernel mode */
#define ARG(i) ((i) < argc ? fields[(i)] : "")

static long susfs_ctl0(const char *ctl_args, char *__user out_msg, int outlen)
{
    if (!ctl_args || !*ctl_args) return -EINVAL;

    /* ctl_args is read-only — copy to a local mutable buffer.  2048 matches
     * the userspace kpm_send() buffer so messages are never truncated. */
    static char buf[2048];
    int n = 0;
    while (ctl_args[n] && n < (int)sizeof(buf) - 1) {
        buf[n] = ctl_args[n];
        n++;
    }
    buf[n] = '\0';

    char *fields[16];
    int argc = split_fields(buf, fields, 16);
    if (argc < 1) return -EINVAL;

    unsigned int cmd;
    if (hex_to_uint(fields[0], &cmd) != 0) {
        return -EINVAL;
    }

    /* show_* commands are pure state and don't touch kernel memory/strings,
     * so they work even if core symbols weren't resolved.  All other
     * commands need memcpy/memset/strcmp/kzalloc/kfree. */
    if (!susfs_core_symbols_ok &&
        cmd != CMD_SUSFS_SHOW_VERSION &&
        cmd != CMD_SUSFS_SHOW_ENABLED_FEATURES &&
        cmd != CMD_SUSFS_SHOW_VARIANT) {
        return -ENOSYS;
    }

    switch (cmd) {
    case CMD_SUSFS_ADD_SUS_PATH:
        return susfs_add_sus_path(ARG(1), 0);
    case CMD_SUSFS_ADD_SUS_PATH_LOOP:
        return susfs_add_sus_path(ARG(1), 1);
    case CMD_SUSFS_ADD_OPEN_REDIRECT:
        if (argc < 4) return -EINVAL;
        return susfs_add_open_redirect(ARG(1), ARG(2),
                                       (int)parse_long(ARG(3), 0));
    case CMD_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU:
        return susfs_set_hide_sus_mnts((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY:
    case CMD_SUSFS_ADD_SUS_KSTAT:
    case CMD_SUSFS_UPDATE_SUS_KSTAT: {
        /* Unified protocol for all sus_kstat commands:
         *   cmd|path|target_ino|spoofed_ino|spoofed_dev|spoofed_nlink|
         *   spoofed_size|spoofed_atime_sec|spoofed_atime_nsec|
         *   spoofed_mtime_sec|spoofed_mtime_nsec|spoofed_ctime_sec|
         *   spoofed_ctime_nsec|spoofed_blocks|spoofed_blksize[|flags]
         * 14 fields after cmd => argc must be >= 15.  An optional 15th
         * field carries the spoof flags (defaults to 0).  Userspace
         * resolves "default" sentinels / current stat values before
         * sending, so the KPM just stores them as-is.  is_static is set
         * only for the _statically variant. */
        if (argc < 15) return -EINVAL;
        int is_static = (cmd == CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY) ? 1 : 0;
        int kflags = (argc >= 16) ? (int)parse_long(ARG(15), 0) : 0;
        return susfs_add_sus_kstat(
            ARG(1),                              /* path */
            parse_ulong(ARG(2), 0),              /* target_ino */
            parse_ulong(ARG(3), 0),              /* spoofed_ino */
            parse_ulong(ARG(4), 0),              /* spoofed_dev */
            (unsigned int)parse_ulong(ARG(5), 0),/* spoofed_nlink */
            (long long)parse_long(ARG(6), 0),    /* spoofed_size */
            parse_long(ARG(7), 0),               /* spoofed_atime_sec */
            parse_ulong(ARG(8), 0),              /* spoofed_atime_nsec */
            parse_long(ARG(9), 0),               /* spoofed_mtime_sec */
            parse_ulong(ARG(10), 0),             /* spoofed_mtime_nsec */
            parse_long(ARG(11), 0),              /* spoofed_ctime_sec */
            parse_ulong(ARG(12), 0),             /* spoofed_ctime_nsec */
            (long long)parse_long(ARG(13), 0),   /* spoofed_blocks */
            parse_long(ARG(14), 0),              /* spoofed_blksize */
            kflags,
            is_static);
    }
    case CMD_SUSFS_ADD_SUS_MAP:
        if (argc < 2) return -EINVAL;
        return susfs_add_sus_map(ARG(1));
    case CMD_SUSFS_SET_UNAME:
        if (argc < 3) return -EINVAL;
        return susfs_set_uname(ARG(1), ARG(2));
    case CMD_SUSFS_SET_CMDLINE_OR_BOOTCONFIG:
        if (argc < 2) return -EINVAL;
        return susfs_set_cmdline_or_bootconfig(ARG(1));
    case CMD_SUSFS_ENABLE_LOG:
        return susfs_set_log_enabled((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_ENABLE_AVC_LOG_SPOOFING:
        return susfs_set_avc_log_spoofing((int)parse_long(ARG(1), 0));
    case CMD_SUSFS_SHOW_VERSION: {
        char tmp[SUSFS_MAX_VERSION_BUFSIZE];
        int rc2 = susfs_show_version(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_ENABLED_FEATURES: {
        char tmp[SUSFS_ENABLED_FEATURES_SIZE];
        int rc2 = susfs_show_enabled_features(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    case CMD_SUSFS_SHOW_VARIANT: {
        char tmp[SUSFS_MAX_VARIANT_BUFSIZE];
        int rc2 = susfs_show_variant(tmp, sizeof(tmp));
        if (rc2 == 0 && out_msg && outlen > 0) {
            int len = 0;
            while (tmp[len] && len < outlen - 1) len++;
            compat_copy_to_user(out_msg, tmp, len + 1);
        }
        return rc2;
    }
    default:
        logke("susfs_kpm: unknown cmd 0x%x\n", cmd);
        return -ENOSYS;
    }
}

KPM_INIT(susfs_init);
KPM_CTL0(susfs_ctl0);
KPM_EXIT(susfs_exit);

/* ===== syscall command channel (bypasses supercall is_authed gate) =====
 *
 * SUPERCALL_KPM_CONTROL requires is_authed, which is only granted to the
 * APatch trusted-manager UID or a correct superkey.  ksu_susfs runs in a
 * root shell (uid 0) — neither — so supercall always returns -EPERM.
 *
 * To let ksu_susfs (and thus the WebUI) actually control the KPM, we hook
 * __NR_kcmp (syscall 272) — a rarely-used syscall (compares two processes'
 * resources) — and use it as a command channel.  When userspace calls:
 *
 *   syscall(272, SUSFS_CMD_MAGIC, cmd_buf_ptr, out_buf_ptr, out_buf_len)
 *
 * the before callback checks the magic; if it matches, it reads cmd_buf
 * from userspace, dispatches via susfs_ctl0(), writes the result to
 * out_buf, and short-circuits the original kcmp syscall.  Non-magic calls
 * pass through to the real kcmp unchanged.
 *
 * __NR_kcmp is chosen because:
 *   - It exists on all Android 4.x+ kernels (arm64).
 *   - Normal apps never call it (it's for debug/analysis tools like perf).
 *   - It takes 5 args (pid1, pid2, type, idx1, idx2) so we have room for
 *     magic + cmd_buf + out_buf + out_len.
 */

#define __NR_kcmp 272
#define SUSFS_CMD_MAGIC 0x5355534653595343ULL /* "SUSFSYSC" */

static void before_cmd_channel(hook_fargs5_t *args, void *udata)
{
    /* On arm64 GKI, has_syscall_wrapper=1 so arg0 is pt_regs*.  Use
     * syscall_argn() to get the real arguments. */
    uint64_t magic = syscall_argn(args, 0);
    if (magic != SUSFS_CMD_MAGIC) return; /* not ours — pass through */

    const char __user *cmd_buf = (const char __user *)syscall_argn(args, 1);
    char __user *out_buf = (char __user *)syscall_argn(args, 2);
    int out_len = (int)syscall_argn(args, 3);

    /* Read command string from userspace */
    char cmd[2048];
    int n = compat_strncpy_from_user(cmd, cmd_buf, sizeof(cmd) - 1);
    if (n <= 0) {
        args->skip_origin = 1;
        args->ret = (uint64_t)(long)-EINVAL;
        return;
    }
    cmd[n] = '\0';

    /* Dispatch via the same ctl0 handler used by supercall */
    long rc = susfs_ctl0(cmd, out_buf, out_len);

    /* Short-circuit the original kcmp syscall; return rc as the result */
    args->skip_origin = 1;
    args->ret = (uint64_t)(long)rc;
}
