#!/usr/bin/env python3
"""Verify that sus_path_duck.txt covers every shared-storage probe path that
Duck-Detector's SharedStorageProbes.kt can build.

Why this exists
---------------
sus_path_duck.txt is the counter-measure for the Duck-Detector shared-storage
probe, and it is generated by tools/gen_sus_path_duck.py.  If the probe ever
gains a spelling that the generator does not emit, the counter-measure silently
stops working: the probe's openat() resolves, the listing succeeds and the
package names HMA hides from PackageManager leak out again.  Nothing in the
module build would fail - the feature would just quietly do nothing, and a
missed path is invisible in the boot log.

This script re-implements the probe's path construction verbatim from
SharedStorageProbes.kt (the source of truth, quoted below) and fails if any of
those exact strings is missing from the shipped file.

Probe source (feature/dangerousapps/data/.../SharedStorageProbes.kt):

    private const val ZERO_WIDTH_SPACE = "\\u200B"
    private val IGNORABLE_CODE_POINTS = listOf(
        "\\u00AD", "\\uFE02", "\\uFE0F", "\\uFEFF", "\\uFFA0",
    )

    // enumerateAndroidDirsByZeroWidthBypass
    val basePath = "/sdcard/Android/data/"
    val bypassPath = basePath.dropLast(1) + ZERO_WIDTH_SPACE + basePath.last()

    // enumerateAndroidDirsByIgnorableCodePoints
    targetDirs = ["/sdcard/Android/data", "/sdcard/Android/obb"]
    bypassPaths = listOf(
        "$targetPath$bypassChar/",
        "/sdcard/${bypassChar}Android/${targetPath.substringAfterLast("/")}",
        "/sdcard$bypassChar/Android/${targetPath.substringAfterLast("/")}",
    )

Run:  python3 tools/check_sus_path_duck.py
Exit status: 0 when every probe path is covered, 1 otherwise.
"""

import pathlib
import sys

ZERO_WIDTH_SPACE = "\u200b"
IGNORABLE_CODE_POINTS = ["\u00ad", "\ufe02", "\ufe0f", "\ufeff", "\uffa0"]

# SharedStorageProbes.enumerateAndroidDirsByZeroWidthBypass()
BASE_PATH = "/sdcard/Android/data/"
ZW_BYPASS = BASE_PATH[:-1] + ZERO_WIDTH_SPACE + BASE_PATH[-1]

# SharedStorageProbes.enumerateAndroidDirsByIgnorableCodePoints()
TARGET_DIRS = ["/sdcard/Android/data", "/sdcard/Android/obb"]


def normalise(path: str) -> str:
    """Trailing slashes are not part of the name: the kernel resolves
    "/a/b/" and "/a/b" to the same dentry, and susfs hides per dentry."""
    return path.rstrip("/")


def probe_paths() -> list:
    """Every path the shared-storage probe can hand to `ls` or openat()."""
    paths = [ZW_BYPASS]
    for target in TARGET_DIRS:
        leaf = target.rsplit("/", 1)[-1]
        for code in IGNORABLE_CODE_POINTS:
            paths.append("%s%s/" % (target, code))
            paths.append("/sdcard/%sAndroid/%s" % (code, leaf))
            paths.append("/sdcard%s/Android/%s" % (code, leaf))
    return paths


def load_listed(path: pathlib.Path) -> dict:
    """Return {normalised path: original line} for the non-comment entries."""
    listed = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        listed[normalise(line)] = raw
    return listed


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    duck = root / "sus_path_duck.txt"
    if not duck.is_file():
        print("[FAIL] %s does not exist - run tools/gen_sus_path_duck.py" % duck)
        return 1

    listed = load_listed(duck)
    missing = []
    for path in probe_paths():
        key = normalise(path)
        if key not in listed:
            missing.append(path)

    total = len({normalise(p) for p in probe_paths()})
    print("[info] shipped entries      : %d" % len(listed))
    print("[info] probe paths checked  : %d" % total)

    if missing:
        print("[FAIL] %d probe path(s) are NOT registered as sus_path:" % len(missing))
        for path in missing:
            print("       %r" % path)
        print("\nAdd the missing spelling to tools/gen_sus_path_duck.py and rerun it.")
        return 1

    print("[ok] every Duck-Detector shared-storage probe path is covered")
    return 0


if __name__ == "__main__":
    sys.exit(main())
