#!/usr/bin/env python3
"""Generate sus_path_duck.txt - the Duck-Detector shared-storage variant list.

Duck-Detector's SharedStorageProbes.kt enumerates /sdcard/Android/{data,obb}
through a path that carries an inserted zero-width space or one of the
"ignorable" code points, e.g.

    /sdcard/Android/data<U+200B>          (ZWC bypass)
    /sdcard/Android/data<U+00AD>          (ignorable code point)
    /sdcard/<U+00AD>Android/data
    /sdcard<U+00AD>/Android/data

The inserted character breaks the FUSE path check while the path still
resolves to the real directory, so the probe's listing succeeds and leaks the
package names that HMA hides from PackageManager ("HMA mismatch").

No legitimate app ever spells a path that way, so registering these variants
as sus_path makes the probe's openat() return -ENOENT and the probe yields
nothing.  boot-completed.sh reads the generated file with its existing
_add_sus_paths helper (which skips the leading "#" header and blank lines).

Run from anywhere:  python3 tools/gen_sus_path_duck.py
"""
import pathlib

CODES = ['\u200B', '\u00AD', '\uFE02', '\uFE0F', '\uFEFF', '\uFFA0']
BASES = ['data', 'obb']
PREFIXES = ['/sdcard', '/storage/emulated/0', '/storage/self/primary']

paths = []
for pre in PREFIXES:
    for c in CODES:
        for b in BASES:
            paths.append('%s/Android/%s%s' % (pre, b, c))   # "data" + ZWC
            paths.append('%s/%sAndroid/%s' % (pre, c, b))   # "/" + ZWC + "Android"
            paths.append('%s%s/Android/%s' % (pre, c, b))   # "/sdcard" + ZWC + "/Android"

dedup = []
for x in paths:
    if x not in dedup:
        dedup.append(x)

HEADER = """# ===== Duck-Detector shared-storage bypass block =====
# SharedStorageProbes.kt enumerates /sdcard/Android/{data,obb} with an
# inserted zero-width space (U+200B) or one of the ignorable code points
# (U+00AD U+FE02 U+FE0F U+FEFF U+FFA0), e.g. "/sdcard/Android/data<U+200B>/".
# The inserted character breaks the FUSE path check while still resolving to
# the real directory, so the listing succeeds and leaks package names that
# HMA hides from PackageManager ("HMA mismatch").
# These variant paths are never used by legitimate apps: registering them
# makes the probe's openat() return ENOENT for that path.
# Auto-generated by tools/gen_sus_path_duck.py - do not edit by hand.
"""

out = pathlib.Path(__file__).resolve().parent.parent / 'sus_path_duck.txt'
out.write_text(''.join([HEADER] + [p + '\n' for p in dedup]))
print('[ok] wrote %s (%d entries)' % (out, len(dedup)))
